add dynamic all-checks-passed

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -58,3 +58,17 @@ jobs:
             echo "file 1 is smaller"
             exit 1
           fi
+
+  all-checks-passed:
+    runs-on: ubuntu-latest
+    needs: [build]
+    if: always()
+    steps:
+      - name: Check status of all required jobs
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') ||
+            contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more dynamic checks failed."
+            exit 1
+          fi
+          echo "All checks passed!"
