Support Java 25 and 26 (#583)
* Java 26

* add dynamic all-checks-passed

* Support 21, 25, and 26

* 25 and 26 only

* fix formatting

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -10,7 +10,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        java-version: [ 25 ]
+        java-version: [ 25, 26 ]
         os: [ ubuntu-latest, macos-latest, windows-latest ]
 
     steps:
@@ -29,7 +29,7 @@ jobs:
       - name: Run Gradle build
         env:
           SPRING_PROFILES_ACTIVE: test
-        run: ./gradlew build --parallel --configuration-cache
+        run: ./gradlew build --parallel --configuration-cache -PjavaVersion=${{ matrix.java-version }}
 
       - name: Generate file
         run: |
@@ -58,3 +58,17 @@ jobs:
             echo "file 1 is smaller"
             exit 1
           fi
+
+  all-checks-passed:
+    runs-on: ubuntu-latest
+    needs: [ build ]
+    if: always()
+    steps:
+      - name: Check status of all required jobs
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') ||
+            contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more dynamic checks failed."
+            exit 1
+          fi
+          echo "All checks passed!"
